version: 2
updates:
  - package-ecosystem: github-actions
    commit-message:
      prefix: "deps"
    directory: /
    labels:
      - automated
      - dependencies
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    commit-message:
      prefix: "deps"
    directory: /go
    labels:
      - automated
      - dependencies
    schedule:
      interval: weekly
